//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WGHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.RoomPrice = new HashSet<RoomPrice>();
        }
    
        public int ID { get; set; }
        public int HOTELID { get; set; }
        public string Name { get; set; }
        public string RoomType { get; set; }
        public string BedType { get; set; }
        public string Facilities { get; set; }
        public Nullable<bool> HasBreakfast { get; set; }
        public Nullable<decimal> Sell { get; set; }
        public string Notice { get; set; }
        public Nullable<int> Quantiy { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomPrice> RoomPrice { get; set; }
    }
}
